# Generated by Django 6.0 on 2026-01-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pass_marks',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
