# Generated by Django 6.0 on 2026-01-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_quiz_pass_marks_alter_quiz_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
